apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app1
  template:
    metadata:
      labels:
        app: react-app1
    spec:
      containers:
        - name: react-app-container1
          image: acrbhoomi.azurecr.io/reactnew:newimage
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
